
import React, { useState, useEffect, useRef } from 'react';
import { PodcastSettings, VoiceName, PodcastEpisode } from '../types';
import { PODCAST_VOICES } from '../constants';
import { Mic2, Play, Pause, Disc, Mic, Sliders, AudioLines, Download, FileAudio, Users, Zap, Terminal, FileText, CheckCircle, Edit3, Rewind, FastForward, Gauge } from 'lucide-react';

interface Props {
    podcast: PodcastEpisode | undefined;
    isGenerating: boolean;
    onGenerate: (settings: PodcastSettings) => void;
    onUpdatePodcast?: (episode: PodcastEpisode) => void;
}

const PodcastStudio: React.FC<Props> = ({ podcast, isGenerating, onGenerate, onUpdatePodcast }) => {
    const [host1, setHost1] = useState<VoiceName>('Puck');
    const [host2, setHost2] = useState<VoiceName>('Kore');
    const [host1Name, setHost1Name] = useState('Host 1');
    const [host2Name, setHost2Name] = useState('Host 2');

    const [style, setStyle] = useState('Investigative & Skeptical');
    const [length, setLength] = useState(2); // 1, 2, 3

    const [isPlaying, setIsPlaying] = useState(false);
    const [playbackSpeed, setPlaybackSpeed] = useState(1);
    const audioRef = useRef<HTMLAudioElement | null>(null);

    // Script Editing State
    const [editingLineIndex, setEditingLineIndex] = useState<number | null>(null);
    const [editingText, setEditingText] = useState('');

    // Hydrate settings from existing podcast if available
    useEffect(() => {
        if (podcast) {
            setHost1(podcast.settings.host1Voice);
            setHost2(podcast.settings.host2Voice);
            setHost1Name(podcast.settings.host1Name || 'Host 1');
            setHost2Name(podcast.settings.host2Name || 'Host 2');
            setStyle(podcast.settings.conversationStyle);
            setLength(podcast.settings.lengthLevel);

            if (podcast.audioUrl && audioRef.current) {
                audioRef.current.src = podcast.audioUrl;
            }
        }
    }, [podcast]);

    // Cleanup: Revoke blob URLs to prevent memory leaks
    useEffect(() => {
        const currentAudioUrl = podcast?.audioUrl;
        return () => {
            if (currentAudioUrl && currentAudioUrl.startsWith('blob:')) {
                URL.revokeObjectURL(currentAudioUrl);
            }
        };
    }, [podcast?.audioUrl]);

    // Handle Playback Speed Changes
    useEffect(() => {
        if (audioRef.current) {
            audioRef.current.playbackRate = playbackSpeed;
        }
    }, [playbackSpeed]);

    const handlePlayPause = () => {
        if (!audioRef.current) return;
        if (isPlaying) {
            audioRef.current.pause();
        } else {
            audioRef.current.play();
        }
        setIsPlaying(!isPlaying);
    };

    const handleGenerate = () => {
        onGenerate({
            host1Voice: host1,
            host2Voice: host2,
            host1Name: host1Name,
            host2Name: host2Name,
            conversationStyle: style,
            lengthLevel: length
        });
    };

    // Update Settings (Names) without regenerating
    const handleNameBlur = () => {
        if (!podcast || !onUpdatePodcast) return;

        const updatedEpisode = {
            ...podcast,
            settings: {
                ...podcast.settings,
                host1Name,
                host2Name
            }
        };
        onUpdatePodcast(updatedEpisode);
    };

    const handleScriptEdit = (index: number) => {
        if (!podcast) return;
        setEditingLineIndex(index);
        setEditingText(podcast.script[index].text);
    };

    const saveScriptLine = () => {
        if (!podcast || editingLineIndex === null || !onUpdatePodcast) return;

        const newScript = [...podcast.script];
        newScript[editingLineIndex] = {
            ...newScript[editingLineIndex],
            text: editingText
        };

        onUpdatePodcast({
            ...podcast,
            script: newScript
        });
        setEditingLineIndex(null);
    };

    const handleDownloadScript = () => {
        if (!podcast) return;

        // Format as Markdown with headers and bold speakers
        const header = `# ${podcast.title}\n\n*Generated by Y-It Podcast Studio*\n\n---\n\n`;
        const content = header + podcast.script.map(line => `**${line.speaker === 'Host 1' ? host1Name : host2Name}**: ${line.text}\n`).join('\n\n');

        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);

        // Sanitize filename
        const safeTitle = podcast.title.replace(/[^a-z0-9]/gi, '_').toLowerCase();

        const a = document.createElement('a');
        a.href = url;
        a.download = `${safeTitle}_script.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const getSafeAudioFilename = () => {
        if (!podcast) return 'episode.wav';
        return `${podcast.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.wav`;
    };

    const cycleSpeed = () => {
        const speeds = [0.75, 1, 1.25, 1.5, 2];
        const currentIndex = speeds.indexOf(playbackSpeed);
        const nextIndex = (currentIndex + 1) % speeds.length;
        setPlaybackSpeed(speeds[nextIndex]);
    };

    return (
        <div className="animate-fadeIn grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Configuration Panel */}
            <div className="lg:col-span-1 space-y-6">
                <div className="bg-gray-900 border border-gray-800 p-6 rounded-xl shadow-lg relative overflow-hidden">
                    {/* Background Accent */}
                    <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/10 blur-[50px] rounded-full"></div>

                    <div className="flex items-center gap-2 mb-6">
                        <Mic2 className="text-purple-500" size={24} />
                        <h2 className="text-xl font-bold tracking-tight">Producer Console</h2>
                    </div>

                    <div className="space-y-6">
                        {/* Voices & Names */}
                        <div className="space-y-3">
                            <label className="text-xs font-bold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                                <Users size={12} /> Casting
                            </label>
                            <div className="grid grid-cols-1 gap-4">
                                <div className="bg-black/50 p-3 rounded border border-gray-700 space-y-2">
                                    <label className="text-xs text-purple-400 font-bold block">Lead Host</label>
                                    <input
                                        type="text"
                                        value={host1Name}
                                        onChange={(e) => setHost1Name(e.target.value)}
                                        onBlur={handleNameBlur}
                                        placeholder="Name (e.g. John)"
                                        className="w-full bg-gray-800 border border-gray-600 rounded px-2 py-1 text-sm focus:border-purple-500 focus:outline-none mb-2"
                                    />
                                    <select value={host1} onChange={(e) => setHost1(e.target.value as VoiceName)} className="w-full bg-transparent text-sm focus:outline-none text-gray-400">
                                        {PODCAST_VOICES.map(v => <option key={v.id} value={v.id}>{v.label}</option>)}
                                    </select>
                                </div>
                                <div className="bg-black/50 p-3 rounded border border-gray-700 space-y-2">
                                    <label className="text-xs text-blue-400 font-bold block">Co-Host / Guest</label>
                                    <input
                                        type="text"
                                        value={host2Name}
                                        onChange={(e) => setHost2Name(e.target.value)}
                                        onBlur={handleNameBlur}
                                        placeholder="Name (e.g. Sarah)"
                                        className="w-full bg-gray-800 border border-gray-600 rounded px-2 py-1 text-sm focus:border-blue-500 focus:outline-none mb-2"
                                    />
                                    <select value={host2} onChange={(e) => setHost2(e.target.value as VoiceName)} className="w-full bg-transparent text-sm focus:outline-none text-gray-400">
                                        {PODCAST_VOICES.map(v => <option key={v.id} value={v.id}>{v.label}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>

                        {/* Narrative Style */}
                        <div className="space-y-3">
                            <label className="text-xs font-bold text-gray-500 uppercase tracking-widest flex items-center gap-2">
                                <Terminal size={12} /> Narrative Directive
                            </label>
                            <textarea
                                value={style}
                                onChange={(e) => setStyle(e.target.value)}
                                className="w-full h-24 bg-black/50 border border-gray-700 rounded p-3 text-sm focus:border-purple-500 focus:outline-none resize-none"
                                placeholder="e.g. Host 1 is skeptical, Host 2 is enthusiastic..."
                            />
                        </div>

                        {/* Length Slider */}
                        <div className="space-y-3">
                            <div className="flex justify-between text-xs">
                                <span className="font-bold text-gray-500 uppercase">Duration</span>
                                <span className="text-purple-400 font-bold">{length === 1 ? "Short (2m)" : length === 2 ? "Standard (5m)" : "Deep Dive (10m)"}</span>
                            </div>
                            <input
                                type="range"
                                min="1"
                                max="3"
                                step="1"
                                value={length}
                                onChange={(e) => setLength(parseInt(e.target.value))}
                                className="w-full h-2 bg-gray-700 rounded-lg accent-purple-500"
                            />
                        </div>

                        <button
                            onClick={handleGenerate}
                            disabled={isGenerating}
                            className="w-full py-4 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-lg shadow-lg shadow-purple-900/20 flex items-center justify-center gap-2 transition-all"
                        >
                            {isGenerating ? <Zap className="animate-spin" /> : <Mic />}
                            {isGenerating ? "Recording Session..." : "Generate Episode"}
                        </button>
                    </div>
                </div>
            </div>

            {/* Player & Transcript */}
            <div className="lg:col-span-2 flex flex-col h-[600px] bg-gray-900 border border-gray-800 rounded-xl overflow-hidden relative">

                {/* Empty State */}
                {!podcast && !isGenerating && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-600 space-y-4">
                        <Disc size={64} className="opacity-20 animate-spin-slow" />
                        <p>No episode recorded.</p>
                        <p className="text-sm max-w-xs text-center">Configure the hosts and click Generate to produce a podcast based on your book.</p>
                    </div>
                )}

                {isGenerating && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/80 z-20">
                        <div className="w-16 h-16 border-4 border-purple-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                        <p className="text-purple-400 font-bold animate-pulse">Recording Session in Progress...</p>
                        <p className="text-xs text-gray-500 mt-2">Generating Script & Synthesizing Audio</p>
                    </div>
                )}

                {/* Player Header */}
                {podcast && (
                    <div className="bg-black/60 backdrop-blur-md p-6 border-b border-gray-800 flex flex-col md:flex-row items-center gap-6 z-10">
                        <div className="flex items-center gap-4">
                            <button
                                onClick={handlePlayPause}
                                className="w-16 h-16 rounded-full bg-purple-500 hover:bg-purple-400 flex items-center justify-center text-white shadow-xl transition-transform hover:scale-105 shrink-0"
                            >
                                {isPlaying ? <Pause size={24} fill="currentColor" /> : <Play size={24} fill="currentColor" className="ml-1" />}
                            </button>

                            <button
                                onClick={cycleSpeed}
                                className="flex flex-col items-center justify-center w-12 h-12 rounded-full bg-gray-800 hover:bg-gray-700 text-xs font-bold text-gray-400 border border-gray-700 transition-colors"
                                title="Playback Speed"
                            >
                                <Gauge size={14} className="mb-0.5" />
                                {playbackSpeed}x
                            </button>
                        </div>

                        <div className="flex-1 w-full text-center md:text-left">
                            <h3 className="text-lg font-bold text-white line-clamp-1">{podcast.title}</h3>
                            <div className="flex items-center justify-center md:justify-start gap-2 text-xs text-gray-400 mt-1">
                                <span className="bg-purple-900/50 text-purple-300 px-2 py-0.5 rounded border border-purple-800">Generated Audio</span>
                                <span>•</span>
                                <span>{new Date(podcast.timestamp).toLocaleDateString()}</span>
                            </div>
                        </div>

                        {/* Export Controls */}
                        <div className="flex items-center gap-3">
                            <button
                                onClick={handleDownloadScript}
                                className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg text-xs font-bold text-gray-300 hover:text-white transition-colors border border-gray-700"
                                title="Download Script as Markdown"
                            >
                                <FileText size={16} /> Script (.md)
                            </button>
                            {podcast.audioUrl && (
                                <a
                                    href={podcast.audioUrl}
                                    download={getSafeAudioFilename()}
                                    className="flex items-center gap-2 px-4 py-2 bg-gray-800 hover:bg-gray-700 rounded-lg text-xs font-bold text-gray-300 hover:text-white transition-colors border border-gray-700"
                                    title="Download Audio as WAV"
                                >
                                    <Download size={16} /> Audio (.wav)
                                </a>
                            )}
                        </div>

                        <audio ref={audioRef} onEnded={() => setIsPlaying(false)} className="hidden" />
                    </div>
                )}

                {/* Visualization Placeholder */}
                {isPlaying && (
                    <div className="h-32 w-full bg-black/80 flex items-center justify-center gap-1 overflow-hidden shrink-0 border-b border-gray-800">
                        {[...Array(30)].map((_, i) => (
                            <div
                                key={i}
                                className="w-2 bg-purple-500 rounded-full animate-music-bar"
                                style={{
                                    height: `${Math.random() * 100}%`,
                                    animationDelay: `${i * 0.05}s`,
                                    opacity: 0.6 + Math.random() * 0.4
                                }}
                            ></div>
                        ))}
                    </div>
                )}

                {/* Transcript */}
                {podcast && (
                    <div className="flex-1 overflow-y-auto p-6 space-y-6 bg-black/20 custom-scrollbar">
                        {podcast.script.map((line, idx) => (
                            <div key={idx} className={`flex gap-4 group ${line.speaker === 'Host 1' ? 'flex-row' : 'flex-row-reverse'}`}>
                                <div
                                    className={`w-10 h-10 rounded-full flex items-center justify-center text-xs font-bold shrink-0 shadow-lg border-2 ${line.speaker === 'Host 1' ? 'bg-purple-600 text-white border-purple-400' : 'bg-blue-600 text-white border-blue-400'}`}
                                    title={line.speaker === 'Host 1' ? host1Name : host2Name}
                                >
                                    {line.speaker === 'Host 1' ? host1Name.charAt(0) : host2Name.charAt(0)}
                                </div>

                                <div className={`relative max-w-[80%] p-4 rounded-2xl text-sm leading-relaxed shadow-md transition-all ${line.speaker === 'Host 1' ? 'bg-gray-800 text-gray-200 rounded-tl-none border border-gray-700 hover:border-purple-500' : 'bg-blue-900/20 text-blue-100 rounded-tr-none border border-blue-900/50 hover:border-blue-500'}`}>
                                    <div className="flex justify-between items-center mb-1">
                                        <div className="text-[10px] font-bold uppercase opacity-50">
                                            {line.speaker === 'Host 1' ? host1Name : host2Name}
                                        </div>
                                        {editingLineIndex !== idx && (
                                            <button onClick={() => handleScriptEdit(idx)} className="opacity-0 group-hover:opacity-100 text-gray-400 hover:text-white transition-opacity">
                                                <Edit3 size={12} />
                                            </button>
                                        )}
                                    </div>

                                    {editingLineIndex === idx ? (
                                        <div className="space-y-2">
                                            <textarea
                                                value={editingText}
                                                onChange={(e) => setEditingText(e.target.value)}
                                                className="w-full bg-black/50 border border-gray-600 rounded p-2 text-white focus:outline-none focus:border-purple-500"
                                                rows={4}
                                                autoFocus
                                            />
                                            <div className="flex justify-end gap-2">
                                                <button onClick={() => setEditingLineIndex(null)} className="text-xs text-gray-400 hover:text-white px-2 py-1">Cancel</button>
                                                <button onClick={saveScriptLine} className="text-xs bg-purple-600 text-white px-3 py-1 rounded font-bold hover:bg-purple-500">Save</button>
                                            </div>
                                        </div>
                                    ) : (
                                        <div onClick={() => handleScriptEdit(idx)} className="cursor-text">
                                            {line.text}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            <style>{`
        @keyframes music-bar {
            0%, 100% { height: 10%; }
            50% { height: 80%; }
        }
        .animate-music-bar {
            animation: music-bar 0.8s ease-in-out infinite;
        }
        .animate-spin-slow {
            animation: spin 8s linear infinite;
        }
        @keyframes spin {
            from { transform: rotate(0deg); }
            to { transform: rotate(360deg); }
        }
        .custom-scrollbar::-webkit-scrollbar { width: 6px; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 3px; }
      `}</style>
        </div>
    );
};

export default PodcastStudio;
